# Generated by Django 4.0.6 on 2022-07-13 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('data_nascimento', models.DateField()),
                ('numero_telefone', models.CharField(max_length=13, verbose_name='telefone')),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, verbose_name='nome')),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidade_1', models.FloatField()),
                ('unidade_2', models.FloatField()),
                ('unidade_3', models.FloatField()),
                ('unidade_4', models.FloatField()),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.aluno')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.materia')),
            ],
        ),
        migrations.AddField(
            model_name='materia',
            name='alunos',
            field=models.ManyToManyField(through='cadastro.Nota', to='cadastro.aluno'),
        ),
    ]
